"""agent tool_calls provider column

ADR-014: the runtime agent is provider-interchangeable (OpenAI or the
Claude API, per AGENT_PROVIDER). `agent.tool_calls` records which adapter
served each call so the audit trail stays legible across a provider
switch and Milestone 6 evals can filter/compare per provider.

NOT NULL with no default: Milestone 5 is the first change that writes to
this table at all, so there are no existing rows to backfill.

Revision ID: 715521e125d4
Revises: fc8bd0e714f9
Create Date: 2026-08-17 20:29:47.887680

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "715521e125d4"
down_revision: str | Sequence[str] | None = "fc8bd0e714f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool_calls", sa.Column("provider", sa.String(length=16), nullable=False), schema="agent"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_calls", "provider", schema="agent")
    # ### end Alembic commands ###
